In [2]:
from pathlib import Path

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px

pd.set_option("display.max_columns", 100)
pd.set_option("display.max_colwidth", 150)

print("Environnement JobPulse AI prêt.")

Environnement JobPulse AI prêt.

In [6]:
#Définir le chemin des données
DATA_DIR = Path("../data/raw")

if not DATA_DIR.exists():
    raise FileNotFoundError(f"Dossier introuvable : {DATA_DIR.resolve()}")

files = list(DATA_DIR.glob("*.csv"))

print(f"Nombre de fichiers CSV trouvés : {len(files)}")

for file in files:
    size_mb = file.stat().st_size / (1024 * 1024)
    print(f"- {file.name} : {size_mb:.2f} MB")

Nombre de fichiers CSV trouvés : 4
- data_science_job_posts_2025.csv : 0.19 MB
- ds_salaries.csv : 0.04 MB
- postings.csv : 492.90 MB
- Resume.csv : 53.67 MB

In [7]:
#Définir le chemin des données
jobs_2025 = pd.read_csv(
    DATA_DIR / "data_science_job_posts_2025.csv",
    low_memory=False
)

salaries = pd.read_csv(
    DATA_DIR / "ds_salaries.csv",
    low_memory=False
)

print("Dataset jobs_2025 :", jobs_2025.shape)
print("Dataset salaries :", salaries.shape)

Dataset jobs_2025 : (944, 13)
Dataset salaries : (607, 12)

In [8]:
#Afficher les premières lignes
display(jobs_2025.head())
display(salaries.head())

,job_title,seniority_level,status,company,location,post_date,headquarter,industry,ownership,company_size,revenue,salary,skills
0,data scientist,senior,hybrid,company_003,"Grapevine, TX . Hybrid",17 days ago,"Bentonville, AR, US",Retail,Public,€352.44B,Public,"€100,472 - €200,938","['spark', 'r', 'python', 'scala', 'machine learning', 'tensorflow']"
1,data scientist,lead,hybrid,company_005,"Fort Worth, TX . Hybrid",15 days ago,"Detroit, MI, US",Manufacturing,Public,"155,030",€51.10B,"€118,733","['spark', 'r', 'python', 'sql', 'machine learning']"
2,data scientist,senior,on-site,company_007,"Austin, TX . Toronto, Ontario, Canada . Kirkland, WA . Orlando, FL . Edmonton, Alberta, Canada + 1 More",a month ago,"Redwood City, CA, US",Technology,Public,"25,930",€33.80B,"€94,987 - €159,559","['aws', 'git', 'python', 'docker', 'sql', 'machine learning', 'gcp', 'kubernetes', 'deep learning']"
3,data scientist,senior,hybrid,company_008,"Chicago, IL . Scottsdale, AZ . Austin, TX . Hybrid",8 days ago,"San Jose, CA, US",Technology,Public,"34,690",€81.71B,"€112,797 - €194,402","['sql', 'r', 'python']"
4,data scientist,NaN,on-site,company_009,On-site,3 days ago,"Stamford, CT, US",Finance,Private,"1,800",Private,"€114,172 - €228,337",[]

,Unnamed: 0,work_year,experience_level,employment_type,job_title,salary,salary_currency,salary_in_usd,employee_residence,remote_ratio,company_location,company_size
0,0,2020,MI,FT,Data Scientist,70000,EUR,79833,DE,0,DE,L
1,1,2020,SE,FT,Machine Learning Scientist,260000,USD,260000,JP,0,JP,S
2,2,2020,SE,FT,Big Data Engineer,85000,GBP,109024,GB,50,GB,M
3,3,2020,MI,FT,Product Data Analyst,20000,USD,20000,HN,0,HN,S
4,4,2020,SE,FT,Machine Learning Engineer,150000,USD,150000,US,50,US,L

In [9]:
#Afficher les colonnes
print("Colonnes jobs_2025 :")
print(jobs_2025.columns.tolist())

print("\nColonnes salaries :")
print(salaries.columns.tolist())

Colonnes jobs_2025 :
['job_title', 'seniority_level', 'status', 'company', 'location', 'post_date', 'headquarter', 'industry', 'ownership', 'company_size', 'revenue', 'salary', 'skills']

Colonnes salaries :
['Unnamed: 0', 'work_year', 'experience_level', 'employment_type', 'job_title', 'salary', 'salary_currency', 'salary_in_usd', 'employee_residence', 'remote_ratio', 'company_location', 'company_size']

In [10]:
#Informations générales
print("Informations jobs_2025")
jobs_2025.info()

print("\nInformations salaries")
salaries.info()

Informations jobs_2025
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 944 entries, 0 to 943
Data columns (total 13 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   job_title        941 non-null    object
 1   seniority_level  884 non-null    object
 2   status           688 non-null    object
 3   company          944 non-null    object
 4   location         942 non-null    object
 5   post_date        944 non-null    object
 6   headquarter      944 non-null    object
 7   industry         944 non-null    object
 8   ownership        897 non-null    object
 9   company_size     944 non-null    object
 10  revenue          929 non-null    object
 11  salary           944 non-null    object
 12  skills           944 non-null    object
dtypes: object(13)
memory usage: 96.0+ KB

Informations salaries
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 607 entries, 0 to 606
Data columns (total 12 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Unnamed: 0          607 non-null    int64
 1   work_year           607 non-null    int64
 2   experience_level    607 non-null    object
 3   employment_type     607 non-null    object
 4   job_title           607 non-null    object
 5   salary              607 non-null    int64
 6   salary_currency     607 non-null    object
 7   salary_in_usd       607 non-null    int64
 8   employee_residence  607 non-null    object
 9   remote_ratio        607 non-null    int64
 10  company_location    607 non-null    object
 11  company_size        607 non-null    object
dtypes: int64(5), object(7)
memory usage: 57.0+ KB

In [11]:
#Valeurs manquantes
missing_jobs = (
    jobs_2025.isnull()
    .sum()
    .sort_values(ascending=False)
)

missing_salaries = (
    salaries.isnull()
    .sum()
    .sort_values(ascending=False)
)

print("Valeurs manquantes dans jobs_2025 :")
display(missing_jobs[missing_jobs > 0])

print("Valeurs manquantes dans salaries :")
display(missing_salaries[missing_salaries > 0])

Valeurs manquantes dans jobs_2025 :

status             256
seniority_level     60
ownership           47
revenue             15
job_title            3
location             2
dtype: int64

Valeurs manquantes dans salaries :

Series([], dtype: int64)

In [12]:
#Doublons
print("Doublons jobs_2025 :", jobs_2025.duplicated().sum())
print("Doublons salaries :", salaries.duplicated().sum())

Doublons jobs_2025 : 0
Doublons salaries : 0

In [13]:
#Statistiques descriptives
display(jobs_2025.describe(include="all").T)

                count unique                          top freq
job_title         941      4               data scientist  856
seniority_level   884      4                       senior  630
status            688      3                      on-site  363
company           944    420                  company_134   30
location          942    431  Bengaluru, Karnataka, India   52
post_date         944     42                  a month ago  167
headquarter       944    197        San Francisco, CA, US   91
industry          944      8                   Technology  582
ownership         897      2                       Public  579
company_size      944    510                          900   18
revenue           929    312                      Private  247
salary            944    896                      €25,214    3
skills            944    400                           []  201

In [14]:
display(salaries.describe(include="all").T)

,count,unique,top,freq,mean,std,min,25%,50%,75%,max
Unnamed: 0,607.0,NaN,NaN,NaN,303.0,175.370085,0.0,151.5,303.0,454.5,606.0
work_year,607.0,NaN,NaN,NaN,2021.405272,0.692133,2020.0,2021.0,2022.0,2022.0,2022.0
experience_level,607,4,SE,280,NaN,NaN,NaN,NaN,NaN,NaN,NaN
employment_type,607,4,FT,588,NaN,NaN,NaN,NaN,NaN,NaN,NaN
job_title,607,50,Data Scientist,143,NaN,NaN,NaN,NaN,NaN,NaN,NaN
salary,607.0,NaN,NaN,NaN,324000.062603,1544357.486636,4000.0,70000.0,115000.0,165000.0,30400000.0
salary_currency,607,17,USD,398,NaN,NaN,NaN,NaN,NaN,NaN,NaN
salary_in_usd,607.0,NaN,NaN,NaN,112297.869852,70957.259411,2859.0,62726.0,101570.0,150000.0,600000.0
employee_residence,607,57,US,332,NaN,NaN,NaN,NaN,NaN,NaN,NaN
remote_ratio,607.0,NaN,NaN,NaN,70.92257,40.70913,0.0,50.0,100.0,100.0,100.0
company_location,607,50,US,355,NaN,NaN,NaN,NaN,NaN,NaN,NaN
company_size,607,3,M,326,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
#Resume.csv

In [15]:

#Inspecter Resume.csv
resume_sample = pd.read_csv(
    DATA_DIR / "Resume.csv",
    nrows=1000,
    low_memory=False
)

print("Dimensions de l'échantillon :", resume_sample.shape)
print("Colonnes :", resume_sample.columns.tolist())

display(resume_sample.head())

Dimensions de l'échantillon : (1000, 4)
Colonnes : ['ID', 'Resume_str', 'Resume_html', 'Category']

,ID,Resume_str,Resume_html,Category
0,16852973,HR ADMINISTRATOR/MARKETING ASSOCIATE\n\nHR ADMINISTRATOR Summary Dedicated Customer Service Manager with 15+ years of experienc...,"<div class=""fontsize fontface vmargins hmargins linespacing pagesize"" id=""document""> <div class=""section firstsection"" id=""SECTION_NAME500375979"" ...",HR
1,22323967,"HR SPECIALIST, US HR OPERATIONS Summary Versatile media professional with background in Communications, Marketing, Human Resou...","<div class=""fontsize fontface vmargins hmargins linespacing pagesize"" id=""document""> <div class=""section firstsection"" id=""SECTION_NAME911808366"" ...",HR
2,33176873,"HR DIRECTOR Summary Over 20 years experience in recruiting, 15 plus years in Human Resources Executive Management, 5 years...","<div class=""fontsize fontface vmargins hmargins linespacing pagesize"" id=""document""> <div class=""section firstsection"" id=""SECTION_NAME1008511259""...",HR
3,27018550,"HR SPECIALIST Summary Dedicated, Driven, and Dynamic with over 20 years of customer service expertise. Motivated to maintain cus...","<div class=""fontsize fontface vmargins hmargins linespacing pagesize"" id=""document""> <div class=""section firstsection"" id=""SECTION_NAME992636658"" ...",HR
4,17812897,HR MANAGER Skill Highlights HR SKILLS HR Department Startup Three New Organization Startups Employment Law FMLA/ADA...,"<div class=""fontsize fontface vmargins hmargins linespacing pagesize"" id=""document""> <div class=""section firstsection"" id=""SECTION_NAME666809417"" ...",HR

In [16]:
resumes = pd.read_csv(
    DATA_DIR / "Resume.csv",
    low_memory=False
)

print("Dataset complet Resume :", resumes.shape)

Dataset complet Resume : (2484, 4)

In [17]:
#postings.csv

In [18]:
#Échantillon de postings.csv
postings_sample = pd.read_csv(
    DATA_DIR / "postings.csv",
    nrows=1000,
    low_memory=False
)

print("Dimensions de l'échantillon :", postings_sample.shape)
print("Colonnes :", postings_sample.columns.tolist())

display(postings_sample.head())

Dimensions de l'échantillon : (1000, 31)
Colonnes : ['job_id', 'company_name', 'title', 'description', 'max_salary', 'pay_period', 'location', 'company_id', 'views', 'med_salary', 'min_salary', 'formatted_work_type', 'applies', 'original_listed_time', 'remote_allowed', 'job_posting_url', 'application_url', 'application_type', 'expiry', 'closed_time', 'formatted_experience_level', 'skills_desc', 'listed_time', 'posting_domain', 'sponsored', 'work_type', 'currency', 'compensation_type', 'normalized_salary', 'zip_code', 'fips']

,job_id,company_name,title,description,max_salary,pay_period,location,company_id,views,med_salary,min_salary,formatted_work_type,applies,original_listed_time,remote_allowed,job_posting_url,application_url,application_type,expiry,closed_time,formatted_experience_level,skills_desc,listed_time,posting_domain,sponsored,work_type,currency,compensation_type,normalized_salary,zip_code,fips
0,921716,Corcoran Sawyer Smith,Marketing Coordinator,Job descriptionA leading real estate firm in New Jersey is seeking an administrative Marketing Coordinator with some experience in graphic design....,20.0,HOURLY,"Princeton, NJ",2774458.0,20.0,NaN,17.0,Full-time,2.0,1.713398e+12,NaN,https://www.linkedin.com/jobs/view/921716/?trk=jobs_biz_prem_srch,NaN,ComplexOnsiteApply,1.715990e+12,NaN,NaN,"Requirements: \n\nWe are seeking a College or Graduate Student (can also be completed with school) with a focus in Planning, Architecture, Real Es...",1.713398e+12,NaN,0,FULL_TIME,USD,BASE_SALARY,38480.0,8540.0,34021.0
1,1829192,NaN,Mental Health Therapist/Counselor,"At Aspen Therapy and Wellness , we are committed to serving clients with best practices to help them with change, improvements and better quality ...",50.0,HOURLY,"Fort Collins, CO",NaN,1.0,NaN,30.0,Full-time,NaN,1.712858e+12,NaN,https://www.linkedin.com/jobs/view/1829192/?trk=jobs_biz_prem_srch,NaN,ComplexOnsiteApply,1.715450e+12,NaN,NaN,NaN,1.712858e+12,NaN,0,FULL_TIME,USD,BASE_SALARY,83200.0,80521.0,8069.0
2,10998357,The National Exemplar,Assitant Restaurant Manager,"The National Exemplar is accepting applications for an Assistant Restaurant Manager.\nWe offer highly competitive wages, healthcare, paid time off...",65000.0,YEARLY,"Cincinnati, OH",64896719.0,8.0,NaN,45000.0,Full-time,NaN,1.713278e+12,NaN,https://www.linkedin.com/jobs/view/10998357/?trk=jobs_biz_prem_srch,NaN,ComplexOnsiteApply,1.715870e+12,NaN,NaN,We are currently accepting resumes for FOH - Asisstant Restaurant Management with a strong focus on delivering high quality customer service. Pref...,1.713278e+12,NaN,0,FULL_TIME,USD,BASE_SALARY,55000.0,45202.0,39061.0
3,23221523,"Abrams Fensterman, LLP",Senior Elder Law / Trusts and Estates Associate Attorney,"Senior Associate Attorney - Elder Law / Trusts and Estates Our legal team is committed to providing each client with quality counsel, innovative ...",175000.0,YEARLY,"New Hyde Park, NY",766262.0,16.0,NaN,140000.0,Full-time,NaN,1.712896e+12,NaN,https://www.linkedin.com/jobs/view/23221523/?trk=jobs_biz_prem_srch,NaN,ComplexOnsiteApply,1.715488e+12,NaN,NaN,"This position requires a baseline understanding of online marketing including Search Engine Marketing, Search Engine Optimization, and campaign an...",1.712896e+12,NaN,0,FULL_TIME,USD,BASE_SALARY,157500.0,11040.0,36059.0
4,35982263,NaN,Service Technician,Looking for HVAC service tech with experience in commerical and industrial equipment. Minimum 5 yrs. on the job with mechanical license. Winger is...,80000.0,YEARLY,"Burlington, IA",NaN,3.0,NaN,60000.0,Full-time,NaN,1.713452e+12,NaN,https://www.linkedin.com/jobs/view/35982263/?trk=jobs_biz_prem_srch,NaN,ComplexOnsiteApply,1.716044e+12,NaN,NaN,NaN,1.713452e+12,NaN,0,FULL_TIME,USD,BASE_SALARY,70000.0,52601.0,19057.0

In [19]:
#Compter les lignes de postings.csv par morceaux
total_rows = 0

for chunk in pd.read_csv(
    DATA_DIR / "postings.csv",
    chunksize=100_000,
    low_memory=False
):
    total_rows += len(chunk)

print("Nombre total de lignes :", total_rows)

Nombre total de lignes : 123849

In [20]:
#Créer un échantillon de travail
postings_work = pd.read_csv(
    DATA_DIR / "postings.csv",
    nrows=50_000,
    low_memory=False
)

print("Échantillon de travail :", postings_work.shape)

Échantillon de travail : (50000, 31)

In [21]:
#Enregistrer cet échantillon
PROCESSED_DIR = Path("../data/processed")
PROCESSED_DIR.mkdir(parents=True, exist_ok=True)

postings_work.to_csv(
    PROCESSED_DIR / "postings_sample_50000.csv",
    index=False
)

print("Échantillon enregistré.")

Échantillon enregistré.

In [22]:
#Résumé automatique des quatre datasets
datasets_summary = []

datasets = {
    "jobs_2025": jobs_2025,
    "salaries": salaries,
    "resume_sample": resume_sample,
    "postings_sample": postings_sample
}

for name, df in datasets.items():
    datasets_summary.append({
        "dataset": name,
        "rows": df.shape[0],
        "columns": df.shape[1],
        "duplicates": int(df.duplicated().sum()),
        "missing_values": int(df.isnull().sum().sum())
    })

summary_df = pd.DataFrame(datasets_summary)

display(summary_df)

           dataset  rows  columns  duplicates  missing_values
0        jobs_2025   944       13           0             383
1         salaries   607       12           0               0
2    resume_sample  1000        4           0               0
3  postings_sample  1000       31           0           11386

In [23]:
#les informations les plus importantes à récupérer
jobs_2025.columns.tolist()
salaries.columns.tolist()
resume_sample.columns.tolist()
postings_sample.columns.tolist()

['job_id',
 'company_name',
 'title',
 'description',
 'max_salary',
 'pay_period',
 'location',
 'company_id',
 'views',
 'med_salary',
 'min_salary',
 'formatted_work_type',
 'applies',
 'original_listed_time',
 'remote_allowed',
 'job_posting_url',
 'application_url',
 'application_type',
 'expiry',
 'closed_time',
 'formatted_experience_level',
 'skills_desc',
 'listed_time',
 'posting_domain',
 'sponsored',
 'work_type',
 'currency',
 'compensation_type',
 'normalized_salary',
 'zip_code',
 'fips']